# Generated by Django 3.1.6 on 2021-02-03 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('one', 'Flat'), ('two', 'Seat'), ('three', 'Sub-let'), ('four', 'mess'), ('five', 'hostel')], max_length=5)),
                ('renter_preference', models.CharField(choices=[('one', 'Family'), ('two', 'Bachelor'), ('three', 'Working Man'), ('four', 'Working Woman'), ('five', 'Anyone')], max_length=5)),
                ('family_member', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6')], max_length=5)),
                ('religion_preference', models.CharField(choices=[('one', 'Islam'), ('two', 'Hinduism'), ('three', 'Christianity'), ('four', 'Buddism'), ('five', 'Anyone')], max_length=5)),
                ('occupation_priority', models.CharField(choices=[('one', 'Service Holder'), ('two', 'Business Man'), ('three', 'Students'), ('five', 'Anyone')], max_length=5)),
                ('address', models.CharField(max_length=150)),
                ('bed_room', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('bed_image', models.ImageField(upload_to='profile_pics')),
                ('drawing_room', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('drawing_image', models.ImageField(upload_to='profile_pics')),
                ('dinning_room', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('dinning_image', models.ImageField(upload_to='profile_pics')),
                ('kitchen', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('kitchen_image', models.ImageField(upload_to='profile_pics')),
                ('bathroom', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('bath_image', models.ImageField(upload_to='profile_pics')),
                ('washing_Machine', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('hot_water', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('IPS', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('Generator', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('Belcony', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('Oven', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('lift', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('refrigerator', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('sofa', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('wifi', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('ac', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('television', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('gas', models.CharField(choices=[('one', 'Pipeline'), ('two', 'Cylinder')], max_length=3)),
                ('security', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('parking', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('house_rent', models.CharField(max_length=10)),
                ('electricity_rent', models.CharField(max_length=5, null=True)),
                ('gas_rent', models.CharField(max_length=5, null=True)),
                ('water_rent', models.CharField(max_length=5, null=True)),
                ('service_rent', models.CharField(max_length=5, null=True)),
                ('any_special_instructions', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
