# Generated by Django 3.1.6 on 2021-02-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='bed_image',
            new_name='bed_room_image',
        ),
    ]
