# Generated by Django 3.1.6 on 2021-02-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210203_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='bath_image',
            new_name='bath_room_image',
        ),
        migrations.RenameField(
            model_name='post1',
            old_name='dinning_image',
            new_name='dinning_room_image',
        ),
        migrations.RenameField(
            model_name='post1',
            old_name='drawing_image',
            new_name='drawing_room_image',
        ),
        migrations.RenameField(
            model_name='post1',
            old_name='kitchen_image',
            new_name='kitchen_room_image',
        ),
    ]
