# Generated by Django 3.1.6 on 2021-02-05 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210203_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
