# Generated by Django 3.1.6 on 2021-02-05 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_post1_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='bathroom',
            field=models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post1',
            name='bed_room',
            field=models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post1',
            name='dinning_room',
            field=models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post1',
            name='drawing_room',
            field=models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post1',
            name='family_member',
            field=models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post1',
            name='kitchen',
            field=models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5),
        ),
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('house_type', models.CharField(choices=[('one', 'Flat'), ('two', 'Seat'), ('three', 'Sub-let'), ('four', 'mess'), ('five', 'hostel')], max_length=5)),
                ('renter_preference', models.CharField(choices=[('one', 'Family'), ('two', 'Bachelor'), ('three', 'Working Man'), ('four', 'Working Woman'), ('five', 'Anyone')], max_length=5)),
                ('family_member', models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8')], max_length=5)),
                ('religion_preference', models.CharField(choices=[('one', 'Islam'), ('two', 'Hinduism'), ('three', 'Christianity'), ('four', 'Buddism'), ('five', 'Anyone')], max_length=5)),
                ('occupation_priority', models.CharField(choices=[('one', 'Service Holder'), ('two', 'Business Man'), ('three', 'Students'), ('five', 'Anyone')], max_length=5)),
                ('address', models.CharField(max_length=150)),
                ('floor', models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10')], max_length=10)),
                ('bed_room', models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('bed_room_image', models.ImageField(upload_to='profile_pics')),
                ('drawing_room', models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('drawing_room_image', models.ImageField(upload_to='profile_pics')),
                ('dinning_room', models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('dinning_room_image', models.ImageField(upload_to='profile_pics')),
                ('kitchen', models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('kitchen_room_image', models.ImageField(upload_to='profile_pics')),
                ('bathroom', models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=5)),
                ('bath_room_image', models.ImageField(upload_to='profile_pics')),
                ('washing_Machine', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('hot_water', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('IPS', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('Generator', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('Belcony', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('Oven', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('lift', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('refrigerator', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('sofa', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('wifi', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('ac', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('television', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('gas', models.CharField(choices=[('one', 'Pipeline'), ('two', 'Cylinder')], max_length=3)),
                ('security', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('parking', models.CharField(choices=[('one', 'Yes'), ('two', 'No')], max_length=3)),
                ('house_rent', models.CharField(max_length=10)),
                ('electricity_rent', models.CharField(max_length=5, null=True)),
                ('gas_rent', models.CharField(max_length=5, null=True)),
                ('water_rent', models.CharField(max_length=5, null=True)),
                ('service_rent', models.CharField(max_length=5, null=True)),
                ('rent_date', models.DateTimeField()),
                ('any_special_instructions', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
