# Generated by Django 3.1.6 on 2021-02-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post3',
            name='bed_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
