# Generated by Django 3.1.6 on 2021-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210205_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post3',
            name='bath_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='post3',
            name='dinning_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='post3',
            name='drawing_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='post3',
            name='kitchen_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
