# Generated by Django 3.1.6 on 2021-02-02 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('one', 'Man'), ('two', 'Woman'), ('three', 'Others')], max_length=5)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('religion', models.CharField(max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('one', 'Unmarried'), ('two', 'Married')], max_length=3)),
                ('nid', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
